environment:
  matrix:
    # Run quick build without recursive testing of dependencies.
    - strawberry_version: 5.24.1.1
      installdeps_options: -n -v
    - strawberry_version: 5.20.3.3 --x86
      installdeps_options: -n -v 
    - strawberry_version: 5.24.1.1
      installdeps_options: -v
    - strawberry_version: 5.24.1.1 --x86
      installdeps_options: -v


build_script:
  - perl -MConfig -E "say $Config{ivsize}"
  - perl -MConfig -E "say $Config{uvsize}"
  
