environment:
  matrix:
    - strawberry_version: 5.24.1.1
    - strawberry_version: 5.22.3.1
    - strawberry_version: 5.20.3.3
    - strawberry_version: 5.18.4.1
install:
  - choco install --allowemptychecksum strawberryperl --version %strawberry_version%
  - path C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
build_script:
  - cpanm --version
  - cpanm App::cpanminus
  - cpanm --version