environment:
  matrix:
    # Run quick build without recursive testing of dependencies.
    - strawberry_version: 5.24.1.1
      installdeps_options: -n -v
    - strawberry_version: 5.20.3.3 --x86
      installdeps_options: -n -v 
    - strawberry_version: 5.24.1.1
      installdeps_options: -v
    - strawberry_version: 5.24.1.1 --x86
      installdeps_options: -v

install:
  - choco install --allowemptychecksum strawberryperl --version %strawberry_version%
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  
build_script:
  - perl -MConfig -E "say $Config{ivsize}"
  - perl -MConfig -E "say $Config{uvsize}"
  - perl -MConfig -E "say $Config{ptrsize}"
  - perl -MConfig -E "say $Config{byteorder}"
  - perl -MConfig -E "say $Config{archname}"
  - perl -MConfig -E "say $Config{osname}"
